CREATE SEQUENCE generacja_id_treningu
start with 1
increment by 1
maxvalue 999999
nocycle;
CREATE SEQUENCE generacja_id_pracownika
start with 1
increment by 1
maxvalue 999999
nocycle;
CREATE SEQUENCE generacja_id_badania
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCYCLE;
CREATE SEQUENCE generacja_id_kontraktu
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCYCLE;
CREATE SEQUENCE generacja_id_obiektu
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCYCLE;
CREATE SEQUENCE generacja_id_meczu
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCYCLE;
CREATE SEQUENCE generacja_id_transferu
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCYCLE;
CREATE SEQUENCE generacja_id_statystyk
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCYCLE;
CREATE SEQUENCE generacja_id_uczestnictwa
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCYCLE;